version: 2
jobs:
  pullsecrets:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - run: git clone https://github.com/davidcrotty/grape
      - run: ls -la
      - persist_to_workspace:
                root: grape
                paths:
                  - config.ru
  build:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - attach_workspace:
                at: grape
      - run: ls -la grape
      - run: gem install fastlane
      - run: fastlane test
  deploy:
     docker:
       - image: circleci/android:api-27-alpha
     steps:
       - run: echo "Deployed"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - pullsecrets
      - build:
          requires:
            - pullsecrets
      - hold:
          type: approval
          requires:
           - build
      - deploy:
          requires:
            - hold