version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: gem install fastlane
      - run: fastlane test
  pullkey:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - run: git clone https://github.com/davidcrotty/grape
      - run: ls -la
      - run: cat grape/config.ru
  deploy:
     docker:
       - image: circleci/android:api-27-alpha
     steps:
       - run: echo "Deployed"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - pullkey
      - build
        requires:
          - pullkey
      - hold:
          type: approval
          requires:
           - build
      - deploy:
          requires:
            - hold