version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - restore_cache: #Checksum onto redownloading deps
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: "Clean & Build Project"
          command: ./gradlew clean build
      - save_cache:
          paths:
            -  ~/.gradle # List of directories which should be added to the cache, gradle stores deps here on CI
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}