version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: gem install fastlane
      - run: fastlane test
  deploy:
    - run: echo "Deployed"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy